# Generated by Django 3.0.5 on 2020-04-12 21:50

import blog.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('place', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=blog.utils.event_picture_path)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.EventType')),
            ],
        ),
    ]
